### ISSUE TITLE
Can it be used to simulate the Ising model or alike?

### ISSUE THREAD

**Issue by liuyxpp** [Julia-Tempering/Pigeons.jl#103]
Suppose I have following high-dimensional integral (a partition function) to be evaluated
```math
\int D\phi(\mathbf{r}) \exp\left[ -H(\phi) \right]
```
where $\phi(\mathbf{r})$ is a density field. In practice, $\phi(\mathbf{r})$ is discretized into a 3D array with millions of elements thus making the integral high-dimensional.

Traditionally we can use Monte Carlo simulations with a metropolis algorithm to evaluate the above integral. I am wondering whether the amazing Pigeons.jl package can be used instead? Thanks!

**Comment by alexandrebouchard** [comment]
Yes this is certainly one of the target applications. After installing the package you can run a simple Ising example with `include("examples/custom-sampler.jl")`. This uses a very basic Ising implementation in https://github.com/Julia-Tempering/Pigeons.jl/blob/main/examples/ising.jl
Let us know if you have any other questions!
