### ISSUE TITLE
n_samples argument

### ISSUE THREAD

**Issue by nikola-sur** [Julia-Tempering/Pigeons.jl#105]
Implementation of `n_samples` as a Pigeons argument. I.e., automatically calculate how many tuning rounds are needed and possibly terminate in the middle of a tuning round to avoid unnecessary additional computation.

**Comment by alexandrebouchard** [comment]
I can see the use of this. But much of the code assumes the current round structure so it might be tricky to get this feature to work with eg resuming checkpoints. So maybe not high priority given the ratio work to benefit.
