### ISSUE TITLE
variable_names does not handle arrays

### ISSUE THREAD

**Issue by itsdfish** [Julia-Tempering/Pigeons.jl#108]
As noted in issue #106, the function `variable_names` does not handle arrays. In MCMCChains.jl, the convention is to do the following 

`variable_names(pt)`

output:

`["v[1]", "v[2]", ...]`

where `v` is a parameter vector. Following the naming convention above is not required, but will allow easy integration with functions in MCMCChains.jl.

**Comment by alexandrebouchard** [comment]
Thanks for raising this! It should be fixed in the just-merged PR
