### ISSUE TITLE
Checkpoints do not restart past round 10

### ISSUE THREAD

**Issue by dchang10** [Julia-Tempering/Pigeons.jl#145]
I recently ran Pigeons v0.2.5 until termination at 10 rounds. I then loaded from the last check point and ran an additional round with:

```
pt= PT(results/all//2023-10-01-01-20-50-VYr2idK4)
pt.inputs.n_rounds += 1
pigeons(pt)
```

This produced in a new results folder with the following contents:

```
results/all/2023-10-02-01-13-40-TQZCljPi/
├── immutables.jls -> ../2023-10-01-01-20-50-VYr2idK4/immutables.jls
├── inputs.jls -> ../2023-10-01-01-20-50-VYr2idK4/inputs.jls
├── round=1 -> ../2023-10-01-01-20-50-VYr2idK4/round=1
├── round=10 -> ../2023-10-01-01-20-50-VYr2idK4/round=10
├── round=11
│   └── checkpoint
│       ├── reduced_recorders.jls
│       ├── replica=10.jls
│       ├── replica=11.jls
│       ├── replica=12.jls
│       ├── replica=13.jls
│       ├── replica=14.jls
│       ├── replica=15.jls
│       ├── replica=16.jls
│       ├── replica=17.jls
│       ├── replica=18.jls
│       ├── replica=19.jls
│       ├── replica=1.jls
│       ├── replica=20.jls
│       ├── replica=2.jls
│       ├── replica=3.jls
│       ├── replica=4.jls
│       ├── replica=5.jls
│       ├── replica=6.jls
│       ├── replica=7.jls
│       ├── replica=8.jls
│       ├── replica=9.jls
│       └── shared.jls
├── round=2 -> ../2023-10-01-01-20-50-VYr2idK4/round=2
├── round=3 -> ../2023-10-01-01-20-50-VYr2idK4/round=3
├── round=4 -> ../2023-10-01-01-20-50-VYr2idK4/round=4
├── round=5 -> ../2023-10-01-01-20-50-VYr2idK4/round=5
├── round=6 -> ../2023-10-01-01-20-50-VYr2idK4/round=6
├── round=7 -> ../2023-10-01-01-20-50-VYr2idK4/round=7
├── round=8 -> ../2023-10-01-01-20-50-VYr2idK4/round=8
└── round=9 -> ../2023-10-01-01-20-50-VYr2idK4/round=9
```

After reloading this folder, I checked the number of rounds in the input to see if it matched the contents of the folder, but `pt.inputs.n_rounds` returned 10. I then tried to add an additional 2 round to `inputs.n_rounds`, bringing the total up to 12. 

```
pt= PT(results/all/2023-10-02-01-13-40-TQZCljPi/)
pt.inputs.n_rounds += 2
pigeons(pt)
```

I then ran pigeons with `pigeons(pt)` under the assumption that it would begin on the 12th round since the 11th round had already completed. This however resulted in pigeons re-running the 11th round.

**Comment by alexandrebouchard** [comment]
Thank you for catching this! I just had a look and I think I know the problem. I'll push a fix shortly..

**Comment by alexandrebouchard** [comment]
Note I had to add a function to increase the number of iterations, `increment_n_rounds!()`.   The change is reflected in the doc at https://pigeons.run/dev/checkpoints/ and there is a new version coming up that will export the symbol. Thanks again for catching this!
