### ISSUE TITLE
Misleading Error prompt when loading from checkpoints.

### ISSUE THREAD

**Issue by dchang10** [Julia-Tempering/Pigeons.jl#154]
I'm not sure if I'm nitpicking, but I think this error message is misleading.

https://github.com/Julia-Tempering/Pigeons.jl/blob/02c1c142e2f223a6db3658404417113678786385/src/pt/checkpoint.jl#L23

This error message will sometimes get called if you try to load the results folder of a previous run, even when checkpoints are available. This can happen, for example, if you tried to load a previous checkpoint without first loading in the dependencies that were initially used. It might be good to elucidated this possibility in the error message.

**Comment by alexandrebouchard** [comment]
That's not nitpicking at all, I fully agree in that scenario this would be a misleading error message. Happy to fix it, probably around early next week. PRs are welcome too if you are interested! 

Thank you and have a great week!

**Comment by dchang10** [comment]
Thanks. I'll put in a pull request in a bit.

**Comment by alexandrebouchard** [comment]
Fixed in #155 - Thanks for the PR!
