### ISSUE TITLE
Exec Folder IO bug when loading MPI runs from checkpoint

### ISSUE THREAD

**Issue by dchang10** [Julia-Tempering/Pigeons.jl#156]
Restarting an MPI run of Pigeons with `PT` from a checkpoint causes each process to create a new exec folder. This seems to happen before MPI is initialized. For example; reloading a run that was initialized with 40 processes will result in 40 new exec folders being made.

https://github.com/Julia-Tempering/Pigeons.jl/blob/02c1c142e2f223a6db3658404417113678786385/src/pt/checkpoint.jl#L33C26-L33C52

UPDATE:

Each process will only write to the folder it created, so the output of each process is written to it's own folder.

**Comment by alexandrebouchard** [comment]
Thanks for catching this! I should be able to get to it soon. That checkpointing is surprisingly tricky...

**Comment by alexandrebouchard** [comment]
Hi Dominic,

I tried reproducing that bug, but I was not able to. If I understand correctly that shows up when an MPI job is being resumed as MPI. You can see what I tried here: https://github.com/Julia-Tempering/Pigeons.jl/pull/157/files

I was wondering if you had a minimal reproducible example for that bug? Thanks again!

**Comment by alexandrebouchard** [comment]
I think with the instructions in the comments of the above PR this should work correctly, but let me know if now.
