### ISSUE TITLE
Recorder for target log_potential

### ISSUE THREAD

**Issue by astrozot** [Julia-Tempering/Pigeons.jl#172]
Apologizes if this has been asked before. Is there any way to retrieve the values of the log_potential corresponding to the samples of the target distribution retrieved by `sample_array(pt)`? That would be useful in various situations, and is what many packages returning MCMCChains do (typically marking the log_potential as an *internal* parameter in the chain).

**Comment by alexandrebouchard** [comment]
Excellent suggestion! I'll try to implement it next week (or feel free to do a PR if you are interested).

**Comment by astrozot** [comment]
Thank you for your fast and kind reply! Unfortunately, I do not know the
code well enough to be able to propose a PR, and therefore, cannot help at
this stage.

Sorry about that…

**Comment by alexandrebouchard** [comment]
Hi Marco! Thanks again for the suggestion, I have implemented it and used your idea also of storing it into the internal parameter in the chain. The PR is just merged, there is not yet a new version for it but should follow soon. 

To implement the suggestion in a nice way, I made MCMCChains an extension dependency, which means you can now just write `my_chain = Chains(pt)` and automatically get the log_density as internal. I have update the doc to specifically show how to plot the log density trace at https://pigeons.run/dev/output-plotting/#Monitoring-the-log-density 

There are some other improvements in the same merged PR to get tighter control on what you want to include in the trace, see https://pigeons.run/dev/output-traces/#Customizing-what-is-saved-in-the-traces

Hope this helps, and I will turn to your other issue as soon as possible!

**Comment by astrozot** [comment]
Hi Alexandre, many thanks for your quick reaction and super-fast implementation! I am looking forward to checking and using the new functionalities!
