### ISSUE TITLE
Possible to run AutoMALA with custom gradient?

### ISSUE THREAD

**Issue by sebapersson** [Julia-Tempering/Pigeons.jl#194]
Thanks for this interesting package!

For a Bayesian inference problem for an ODE model in biology I would like to test Pigeon.jl. As explorer I would like to use `AutoMALA` (as all my variables are continuous and unbound). For my log-posterior I can provide a custom gradient that is more efficient than using autodiff (e.g. `ForwardDiff`). 

However, I have checked the documentation https://pigeons.run/dev/reference/#Pigeons.AutoMALA and I have not found whether or not it is possible to provide a custom gradient. Would providing a gradient to a `LogDensityProblem` work:

```julia
function LogDensityProblems.logdensity_and_gradient(problem::MyLogPotential, x)
    logdens = ...
    grad = ...
    return logdens, grad
end
```

**Comment by alexandrebouchard** [comment]
It should indeed be relatively straightforward!

We actually use just that for the toy_mvn_target (used internally to test allocation properties of autoMALA against regressions). 

You can base of your implementation on 

https://github.com/Julia-Tempering/Pigeons.jl/blob/main/src/targets/toy_mvn_target.jl

combined with 

https://github.com/Julia-Tempering/Pigeons.jl/blob/484c9d10b101818724303f7816457286e9da9ac0/src/paths/ScaledPrecisionNormalPath.jl#L24

Let me know if you encounter any road blocks!

**Comment by sebapersson** [comment]
Thanks for the fast reply, I managed to get it working!

Providing a custom gradient to `AutoMala` is a bit involved, would it be possible to add a custom gradient option?

**Comment by alexandrebouchard** [comment]
Agreed that at the very least we should give an example in the documentation!
