### ISSUE TITLE
Discrete and mixed priors

### ISSUE THREAD

**Issue by aplavin** [Julia-Tempering/Pigeons.jl#195]
Thanks for this inference package! I had some success using it for problems with all continuous parameters, trying to incorporate discrete ones as well.

I noticed that the api docs mention discrete variables a few times, but didn't find anything concrete in how they work, and what options to choose. Also, can Pigeons support "mixed" variables, such as spike-slab priors?
A few cases I have in mind:
1. Spike-slab prior, something like `x ~ Normal(0, 1) + point mass at 0`. Can such a variable be defined in Pigeons directly?
2. Discrete 0/1 flag variable, for example as an alternative implementation for spike-slab. So that the prior is:
```
z ~ Bernoulli(0.5)
y ~ Normal(0, 1)
x = z * y
```
How to define such a discrete variable, how to tell Pigeons about its domain, will it correctly infer the y-z connection?
3. General discrete variables, priors like `x ~ DiscreteUniform(0, 15)`.

Would appreciate any help, suggestions, or advice!

**Comment by alexandrebouchard** [comment]
Thanks for asking! Yes, it is indeed possible to use Pigeons with mixed continuous discrete variables, in particular the spike-and-slab will work. 

As a starting point, the simplest route would be to write your model via Turing (https://pigeons.run/dev/input-turing/). In your example, Turing and Pigeons will correctly deduce to use a slice sampler for the normal, and a specialized discrete sampler for the binary (inside the hood, this is done via different dispatch on the following function: https://github.com/Julia-Tempering/Pigeons.jl/blob/484c9d10b101818724303f7816457286e9da9ac0/src/explorers/SliceSampler.jl#L65). Similarly, discrete uniform distributions will be handled with a specialized sampler, namely an integer slicer also in the same SliceSampler file. 

Let me know if you encounter any difficulties!

**Comment by alexandrebouchard** [comment]
Yes, that's certainly possible too. Here is the approach I would suggest: create a custom "explorer" following the structure used in https://pigeons.run/dev/input-explorers/ where the implementation of `Pigeons.step!` could for example call inside the Pigeons.step! function, you can call the function:

- for bool: https://github.com/Julia-Tempering/Pigeons.jl/blob/484c9d10b101818724303f7816457286e9da9ac0/src/explorers/SliceSampler.jl#L65 
- for integer/real: https://github.com/Julia-Tempering/Pigeons.jl/blob/484c9d10b101818724303f7816457286e9da9ac0/src/explorers/SliceSampler.jl#L89

Here is a rough template:

```
function Pigeons.step!(explorer::MyIndependenceSampler, replica, shared)
    log_potential = find_log_potential(replica, shared.tempering, shared)
    sampler = SliceSampler(...)
    state = replica.state
    rng = replica.rng
    continuous = # access part of the state that is say a vector 
    cached_lp = -Inf
    for i in eachindex(continuous) 
        pointer = Ref(continuous, i)
        cached_lp = slice_sample_coord!(sampler , replica, pointer, log_potential, cached_lp, typeof(pointer[]))
    end 
    # similarly for the discrete/bernoulli part
end
```

Hope this helps!

**Comment by alexandrebouchard** [comment]
The slice sampler does that with Turing models, yes (see https://github.com/Julia-Tempering/Pigeons.jl/blob/484c9d10b101818724303f7816457286e9da9ac0/ext/PigeonsDynamicPPLExt/state.jl#L8 for additional details on how it works in that case). But outside of Turing models I think you would have to add a small function like the one I sketched in the above post.

**Comment by alexandrebouchard** [comment]
Emergent behaviour! ;) That's great to hear, thank you for reporting that. I should document that...

**Comment by miguelbiron** [comment]
Hi @aplavin -- just to complement Alex's comment, we do in fact support the `Vectlor{Real}` approach, but it is not well documented (see e.g. [this test case](https://github.com/Julia-Tempering/Pigeons.jl/blob/f363507f08e60df582750b198b9f49cbd8f5d34a/test/test_slice_sampler.jl#L68)). Nevertheless, note that there might be a performance hit by using as state a Vector with non-concrete eltype. Using Alex's approach via a user-defined struct can solve this. In the end, it is a trade-off between efficiency and simplicity of implementation.

**Comment by miguelbiron** [comment]
Exactly, that is the standard way of implementing a spike-and-slab type prior. Let us know if you hit any issues using it.
