### ISSUE TITLE
Non-concrete field in TuringLogPotential

### ISSUE THREAD

**Issue by miguelbiron** [Julia-Tempering/Pigeons.jl#20]
The type `DynamicPPL.Model` of the `model` field here

https://github.com/Julia-Tempering/Pigeons.jl/blob/47db70ebdeb915ab1ae14cf6142611dd4f2fde97/src/targets/TuringLogPotential.jl#L2

is not specific enough because Model is parametrized; see [here](https://github.com/TuringLang/DynamicPPL.jl/blob/6d5dc4028db6831f6ddbec8544e825a91aad816c/src/model.jl#L34). This might cause extra allocations since the compiler may not be able to do inference properly.

Easy fix would be to do something like

```julia
struct TuringLogPotential{TModel <: DynamicPPL.Model}
    model::TModel
    only_prior::Bool
end
```

**Comment by alexandrebouchard** [comment]
Thanks! Will include this in my current dev branch to be merged soon.
