### ISSUE TITLE
Add Documentation for using @addlogprob! correctly

### ISSUE THREAD

**Issue by itsdfish** [Julia-Tempering/Pigeons.jl#206]
Issue #201 describes a problem with using `@addlogprob!`. The solution was to wrap it in a conditional:

```
if DynamicPPL.leafcontext(__context__) !== DynamicPPL.PriorContext() 
       @addlogprob! ....
end
```
This would be great to add to the documentation.

**Comment by nikola-sur** [comment]
Thank you for this comment! This would be very useful to add to the documentation because other users seem to have run into this. Feel free to create a PR or I can set that up later.

**Comment by itsdfish** [comment]
Seems easy enough. I will submit a PR in a few days.
