### ISSUE TITLE
defining how to sample the initial parameter values

### ISSUE THREAD

**Issue by schminin** [Julia-Tempering/Pigeons.jl#212]
Since we have made very good experiences with starting from somewhat informed initial parameter values especially when working with correlated parameter spaces, I was wondering whether this functionality already exists in Pigeons.jl (I couldn't find it anywhere) or whether you're planing to incorporate this soon.

**Comment by alexandrebouchard** [comment]
Sorry for the delay! 

Yes, there is a method to provide initialization, that is: 

https://pigeons.run/dev/reference/#Pigeons.initialize-Tuple{Any,%20Random.AbstractRNG,%20Int64} 

Happy to provide a more detailed explanation of how to use it (and improve the doc at the same time), but it might be easier if you have a bit more information on the type of target you are using (Stan, Turing, or something else?).

**Comment by schminin** [comment]
Thank you for your reply. If you find the time for it a more detailed explanation of how to use it would be great! I am defining a model using Turing, i.e. very similar to [this](https://pigeons.run/dev/input-turing/).

**Comment by alexandrebouchard** [comment]
My pleasure! Here is an example of how you can proceed:

```
using DynamicPPL, Pigeons, Distributions, DistributionsAD

DynamicPPL.@model function toy_beta_binom_model(n_trials, n_successes)
    p ~ Uniform(0, 1)
    n_successes ~ Binomial(n_trials, p)
    return n_successes
end

function toy_beta_binom_target(n_trials = 10, n_successes = 2)
    return Pigeons.TuringLogPotential(toy_beta_binom_model(n_trials, n_successes))
end

const ToyBetaBinomType = typeof(toy_beta_binom_target())

function Pigeons.initialization(target::ToyBetaBinomType, rng::AbstractRNG, ::Int64) 
    result = DynamicPPL.VarInfo(rng, target.model, DynamicPPL.SampleFromPrior(), DynamicPPL.PriorContext())
    DynamicPPL.link!!(result, DynamicPPL.SampleFromPrior(), target.model)

    # custom init goes here: for example here setting the variable p to 0.5
    Pigeons.update_state!(result, :p, 1, 0.5)

    return result
end

pt = pigeons(target = toy_beta_binom_target(), n_rounds = 0)
@assert Pigeons.variable(pt.replicas[1].state, :p) == [0.5]
```

I'm in the process of adding it to the documentation.

**Comment by alexandrebouchard** [comment]
I'm so glad to hear! Have a good one :)
