### ISSUE TITLE
Informal interface for target should use `initialization` instead of `initialize`

### ISSUE THREAD

**Issue by bencwallace** [Julia-Tempering/Pigeons.jl#223]
The informal interface for a target [declares](https://github.com/Julia-Tempering/Pigeons.jl/blob/1d4e0bc5ff54d78ce2f99e4fa9fdfcaca515527d/src/targets/target.jl#L13) a function called `initialize`. This name doesn't seem to be used anywhere else in the code base and all concrete targets appear to define a method called `initialization`. Unless I'm missing something here, the simplest way to resolve this discrepancy would be to change `initialize` to `initialization` in the line linked to above.
Happy to open a PR with this small modification if desired.

**Comment by nikola-sur** [comment]
Yes, thank you! I noticed this discrepancy a few days ago, as well. If you can open a PR that would be great. Otherwise, I can do it -- should be a quick change.

**Comment by bencwallace** [comment]
Sure, I don't mind, I'll go ahead and do that.
