### ISSUE TITLE
Add KS test for samplers

### ISSUE THREAD

**Issue by miguelbiron** [Julia-Tempering/Pigeons.jl#240]

**Comment by miguelbiron** [comment]
Reference: [https://ubc-stat-ml.github.io/web447/w12_mcmc2/topic08_debug.html](https://github.com/Julia-Tempering/Pigeons.jl/issues/zoom_custom_url=1&zoom_im_wrapper_url=1&originalUrl=aHR0cHM6Ly91YmMtc3RhdC1tbC5naXRodWIuaW8vd2ViNDQ3L3cxMl9tY21jMi90b3BpYzA4X2RlYnVnLmh0bWw%3D&isInsertLink=0&originalText=https://ubc-stat-ml.github.io/web447/w12_mcmc2/topic08_debug.html&seq=2)

**Comment by trevorcampbell** [comment]
@miguelbiron that link is broken for me FYI

**Comment by trevorcampbell** [comment]
(but this is an excellent idea, big +1 from me)

**Comment by alexandrebouchard** [comment]
Fixed the link!

**Comment by miguelbiron** [comment]
Thanks @alexandrebouchard ! Do you have a reference for the Markov chain KS test that you talked about?

**Comment by miguelbiron** [comment]
Example Blang implementation: https://github.com/UBC-Stat-ML/blangSDK/blob/master/src/main/java/blang/validation/ExactInvarianceTest.java

**Comment by alexandrebouchard** [comment]
The Blang paper, Section 10.5: https://www.jstatsoft.org/article/view/v103i11

**Comment by miguelbiron** [comment]
Thanks!
