### ISSUE TITLE
Export and document the explorer invariance tests

### ISSUE THREAD

**Issue by miguelbiron** [Julia-Tempering/Pigeons.jl#252]
They might be useful for some users.

**Comment by alexandrebouchard** [comment]
I agree it would be good to document it. Re exporting, I think it is niche enough that it's OK for now to keep it as a Pigeons.xy feature...

**Comment by miguelbiron** [comment]
Look like your PR #272 @alexandrebouchard  already closes this?

**Comment by alexandrebouchard** [comment]
Good point, thanks!
