### ISSUE TITLE
DynamicPPL targets: only link! the varinfo if using gradient-based samplers

### ISSUE THREAD

**Issue by miguelbiron** [Julia-Tempering/Pigeons.jl#254]
Could save time and allocations by not going back and forth between spaces

**Comment by miguelbiron** [comment]
Drawback: will fail when any distribution in the constrained space lives in a submanifold of the ambient space; e.g., Dirichlet.

**Comment by alexandrebouchard** [comment]
Good point.. seems better not to do this then. Just to double-check, this was just a suggestion, was not actually implemented? Then I suggest we close that issue.

**Comment by miguelbiron** [comment]
Yep, not implemented. Closing now!
