### ISSUE TITLE
Inexact error in slice sampler with integer variables

### ISSUE THREAD

**Issue by trevorcampbell** [Julia-Tempering/Pigeons.jl#263]
MWE:
```
DynamicPPL.@model function test()
    p ~ Categorical(0.1*ones(10))
end
test_target = TuringLogPotential(test())
inputs = Inputs(target = test_target,
                explorer = SliceSampler(w = 0.1, p = 20, n_passes = 1, max_iter = 1_024)
                )
pt = pigeons(inputs)
```

You'll get an error from `slice_accept`. The underlying issue here is that `w=0.1` doesn't work with integer variables (`slice_accept` will try to shrink the slice below size 1 and fail). 

The solution is probably to check for integer variables, and for those variables force w to be max(w, 1.1) or something like that.

**Comment by alexandrebouchard** [comment]
Good point! Pushing a better error message...
