### ISSUE TITLE
Remove allocations in reference chain for Turing models

### ISSUE THREAD

**Issue by nikola-sur** [Julia-Tempering/Pigeons.jl#27]
See `initialization()` on lines 33 and 41
https://github.com/Julia-Tempering/Pigeons.jl/blob/4be2944b802836d164339f3e64a40573e7c6be37/src/targets/TuringLogPotential.jl#L32-L42

**Comment by alexandrebouchard** [comment]
Since Turing has many allocations internally, I am not sure if this will lead to performance improvement...
