### ISSUE TITLE
Error/warning behaviour for NaN logprobs

### ISSUE THREAD

**Issue by trevorcampbell** [Julia-Tempering/Pigeons.jl#296]
I was just running an experiment and came across the following error:

```
─────────────────────────────────────────────────────────────────────────────────────────────────────────────
  scans     restarts      Λ        time(s)    allc(B)  log(Z₁/Z₀)   min(α)     mean(α)    min(αₑ)   mean(αₑ) 
────────── ────────── ────────── ────────── ────────── ────────── ────────── ────────── ────────── ──────────
        2          0       1.98      0.856   2.45e+09  -4.73e+04          0      0.718          1          1 
        4          0       3.99       1.81   4.37e+09       -227   4.31e-17       0.43          1          1 
        8          0       5.35       3.21   8.81e+09       -224   1.62e-48      0.235          1          1 
       16          0       5.18       6.83   1.71e+10       -175   1.38e-09      0.261          1          1 
       32          0       5.33       13.1   3.42e+10       -180   2.42e-07      0.239      0.999          1 

AssertionError: Bad intensities: [NaN, 0.5959981856055306, 0.8382298501276826, 0.5945987852903227, 0.8575147150936844, 0.9602120626716961, 0.33528416810082795]

Stacktrace:
  [1] optimal_schedule_generator(intensity::Vector{Float64}, old_schedule::Vector{Float64}, nudged::Bool)
    @ Pigeons ~/.julia/packages/Pigeons/UUYm9/src/tempering/adaptation.jl:76
  [2] optimal_schedule_generator
    @ ~/.julia/packages/Pigeons/UUYm9/src/tempering/adaptation.jl:75 [inlined]
  [3] optimal_schedule(intensity::Vector{Float64}, old_schedule::Vector{Float64}, new_schedule_n_chains::Int64)
    @ Pigeons ~/.julia/packages/Pigeons/UUYm9/src/tempering/adaptation.jl:89
(etc etc etc)
```

I found the error to be confusing---it comes from the schedule generator, and looks like it might be a bug in Pigeons itself in how it computes the next schedule. But actually the problem was mine -- I had a NaN in my logprob computation.

This leads to a few suggested changes:

- catch NaN logprobs earlier (i.e., right when we ask for them) so users know the problem is in their code
- default to error out on NaN. Print the state value, and suggest how to fix the problem.
    - e.g.: "at parameter value [report the parameter], logprob was nan. Please double-check your logprob computation for bugs, or catch expected NaNs and report a finite value or -Inf for a zero probability state. Alternatively, you can set NaNs to be treated as -Inf by ...."  
- Give an option in the API to switch NaNs to a warning instead of an error, and treat them as `-Inf`.

**Comment by miguelbiron** [comment]
Hey @trevorcampbell -- since we caught this same issue in the JuliaBUGS implementation, we decided to add a fix there and kill 2 birds with 1 stone. As you suggested, the idea is to catch the issue much earlier, and give some more information on the cause. Here's the change

https://github.com/Julia-Tempering/Pigeons.jl/commit/d4a60711a49618bcd6e21e1ff93ee87495fd7ad3#diff-a04db0e27c431f01075795ada4b635c583a5b7ad7f246be85f9297cd1d259be9
