### ISSUE TITLE
(Unnecessary) allocation in inner loop

### ISSUE THREAD

**Issue by nikola-sur** [Julia-Tempering/Pigeons.jl#38]
`continuous_variables(state)` is allocating for e.g. Turing models. This is why I was motivated to create the mutable global constant `CONTINUOUS_VARS`. You can see below that the recorder calls `continuous_variables()`
https://github.com/Julia-Tempering/Pigeons.jl/blob/e1c66111190961b34d7b7ab36a042382ac6154ad/src/recorders/OnlineStateRecorder.jl#L51-L61

For Turing models:
https://github.com/Julia-Tempering/Pigeons.jl/blob/e724069275a874ed3679f51c27f67d7573414c97/src/pt/state.jl#L62-L79

@alexandrebouchard

**Comment by alexandrebouchard** [comment]
Good to know! Still, instead of being global, they could be stored in TuringPotential isn't it?

**Comment by nikola-sur** [comment]
For the recorders, we need `continuous_variables(state)` instead of `continuous_variables(log_potential)`. 
Because this is already allocating for Turing models, I might as well remove the global CONTINUOUS_VARS and not bother making `continuous_variables(log_potential)` non-allocating?

**Comment by nikola-sur** [comment]
I should mention that the only states AFAIK for which I really need CONTINUOUS_VARS in order to prevent allocations is for Turing models. Seeing that Turing makes so many unnecessary allocations I might as well not bother..

**Comment by alexandrebouchard** [comment]
Fair enough!
