### ISSUE TITLE
Option dim_fraction in SliceSampler has no effect, moreover default of one pass is problematic

### ISSUE THREAD

**Issue by alexandrebouchard** [Julia-Tempering/Pigeons.jl#44]
First issue: SliceSampler advertises an option to adjust the number of passes per exploration, but it is not used anywhere. It is better to introduce options only when they are used and work as advertised.

Second closely related issue: in a 1d normal, 1 pass of slice sampling per expl step seems insufficient as it gives max|ρ| = 0.911, mean|ρ| = 0.474. Compare this to the following (max, mean)

2 passes: 0.777      0.239 
3 passes: 0.105     0.0377
4 passes: 0.0797     0.0316

So it seems using Blang's default of 3 in this example would be much more reasonable.

**Comment by alexandrebouchard** [comment]
One option is to simplify it to ``n_passes::Int`` instead of fraction and something of the style

```
function step!(explorer::SliceSampler, replica, shared)
    for i in 1:explorer.n_passes
        log_potential = find_log_potential(replica, shared)
        slice_sample!(explorer, replica.state, log_potential, replica.rng) 
    end
end
```

**Comment by nikola-sur** [comment]
Thanks for catching this. I removed the `dim_fraction` option was originally to only update a fraction (e.g. 50%) of the variables but I removed it when making the SliceSampler non-allocating. I added the `n_passes` option now and am waiting for tests to pass on the branch. The default values is `n_passes = 3` now.
