### ISSUE TITLE
Faster slice sampling by caching `log_potential` calls

### ISSUE THREAD

**Issue by trevorcampbell** [Julia-Tempering/Pigeons.jl#61]
It looks like there is quite a bit of redundant `log_potential` computations that could be saved in `SliceSampler.jl`. This isn't super high priority for now, but if we run into an example where `log_potential` is very expensive, this sampler could be made a lot faster than it is now.

E.g. in the outer loop -- we should only re-compute `log_potential` if the state changed, and even then the log potential for the new state is already computed somewhere deep inside of `slice_accept`:
```julia
function slice_sample!(h::SliceSampler, state::AbstractVector, log_potential, rng)
    for c in 1:length(state) # update *every* coordinate
        g_x0 = log_potential(state)
        pointer = Ref(state, c)
        slice_sample_coord!(h, state, pointer, log_potential, g_x0, rng)
    end
end
```

In Bernoulli sample coord: we don't need to re-compute `log_potential(state)` for each of 0 and 1 -- just pass in `g_x0` from `slice_sample_coord!` and compute the one we don't yet have:
```julia
function Bernoulli_sample_coord!(state, pointer, log_potential, rng)
    pointer[] = Bool(0)
    log_potent_0 = log_potential(state)
    pointer[] = Bool(1)
    log_potent_1 = log_potential(state)
    log_ratio = log_potent_0 - log_potent_1
    if rand(rng) < log_ratio/(1+log_ratio)
        pointer[] = Bool(0)
    end # otherwise already set to 1
end
```

Same with all the doubling/shrinking steps -- basically any time something doesn't move, we shouldn't recompute the log potential for that.

**Comment by trevorcampbell** [comment]
(I'm actually about to code a slice sampler for another project -- so instead of doing it from scratch, I'll try to improve this one and make a PR)

**Comment by alexandrebouchard** [comment]
+1 on that one! 

Also, talking of slicers improvements, probably would be a good idea to adjust each dimension's initial window size from the previous round in the style of a diagonal mass matrix adaptation (which is implemented in better-hmc and trivial to do using the target_online recorder).
