### ISSUE TITLE
Bug in slice sampler

### ISSUE THREAD

**Issue by trevorcampbell** [Julia-Tempering/Pigeons.jl#62]
I believe this line is wrong -- needs to have an exp transform in there somewhere. I'll fix it as part of number #64 

https://github.com/Julia-Tempering/Pigeons.jl/blob/6fa8268b8af5df804faaee59c7ab887688dd872c/src/explorers/SliceSampler.jl#L74

**Comment by alexandrebouchard** [comment]
Good catch! @nikola-sur, I propose that we use this as an opportunity to first write a test that would have detected that bug

**Comment by nikola-sur** [comment]
Sounds good! I'll put that on a Pigeons TODO list.
