### ISSUE TITLE
Example of custom implementation

### ISSUE THREAD

**Issue by Gkreindler** [Julia-Tempering/Pigeons.jl#80]
Hello,

Thank you for what looks like an amazing package!

My research team is interested in using Pigeons.jl to sample from a non-convex, discrete distribution $\pi_N(X) = \exp(\beta U(X)) / Z$ where $Z=\sum_Y \exp(\beta U(Y))$ where $X$ are combinatorial objects (belonging to a high-dimensional, finite set). Suppose we have a Julia function $U(X)$, and a kernel $\Psi(X' | X)$ that proposes network modifications. The parameter $\beta$ is just given.

(1) How can we use these objects ($U, \Psi, \beta$) to define a custom target? We are trying to use the example given here but it's unclear to us where to put $\Psi$. Presumably in line 17? But what kind of object is that?
https://github.com/Julia-Tempering/Pigeons.jl/blob/main/examples/general-target.jl

(2) Do we need to be able to do iid from $\pi_1$? We are thinking of $\pi_j$ corresponding to $\beta_j$ with $\beta_1<\dots<\beta_N$ but we are not able to randomly sample networks even for $\beta_0=0$.

Any help/tips would be much appreciated!

cc @Lliillyy

**Comment by alexandrebouchard** [comment]
Thanks, and glad this may be useful!

I wrote an example (https://github.com/Julia-Tempering/Pigeons.jl/blob/main/examples/custom-sampler.jl) based on the Ising model to illustrate how to specify the kernel \Psi described in your question (we call those "exploration kernels" in the code base): in the Ising example see 
https://github.com/Julia-Tempering/Pigeons.jl/blob/587af2761bdc3914915fde82cc3c8a014954d47c/examples/custom-sampler.jl#L99 
The same example also shows how U is defined:
https://github.com/Julia-Tempering/Pigeons.jl/blob/587af2761bdc3914915fde82cc3c8a014954d47c/examples/custom-sampler.jl#L74

As for beta, it will be adapted automatically. More precisely, the code will automatically construct a continuum of distributions p_beta(x) propto p_ref^(1-beta)(x) p_target^beta(x) between a "reference" p_ref and a target p_target. For example in the Ising model the reference consists in iid Bernoulli r.v.s. The method automatically discretizes the continuum and maintains one MCMC chain for each intermediate distribution (let us know if you would like pointers for background on PT). 

It is not strictly necessary to do iid sampling at beta = 0. You can start by implementing the iid method as a no-operation function. However it can be quite useful to jump across the state space. The good news is that you have a lot of freedom on how to choose p_ref. Even if the model is quite complex, all you strictly need to get basic theoretical guarantees (consistency) is that p_ref should have the same support as the target and you should be able to sample and evaluate it. 

Hope this helps! Let us know if anything is unclear.

**Comment by nikola-sur** [comment]
It seems that `default_explorer` might have been introduced after our latest official release from March. Maybe try using the latest release on GitHub? Does running 
```julia
]remove Pigeons
```
and then
```julia
]add https://github.com/Julia-Tempering/Pigeons.jl.git
``` 
work? Sorry about that! We will work on releasing a new version soon.

**Comment by alexandrebouchard** [comment]
A priori, StanBridge should support windows (our continuous integration tests are successful on windows at the moment) but indeed one of us mentioned he had an issue as well related to windows+BridgeStan (@nikola-sur).

We will investigate this! @nikola-sur is it a similar problem that you had? If so, maybe we could chat today to try to drill down the source of the problem on your laptop (I don't have a windows machine unfortunately).

One possible guess: I remember some cases where having a space in a path caused a problem on windows?

**Comment by Gkreindler** [comment]
Thank you! We'll try on a Mac, and on Windows without spaces (I should know better: when have spaces ever been anything but trouble?)

**Comment by nikola-sur** [comment]
@alexandrebouchard: On Windows I can successfully download/install BridgeStan, but I had a different issue with compilation of the Stan models.

@Gkreindler: Hopefully without spaces on Windows or on a Mac the issue should be resolved. If issues persist it might be worth checking the following BridgeStan requirements: https://roualdes.github.io/bridgestan/latest/getting-started.html#requirement-c-toolchain

**Comment by Lliillyy** [comment]
@nikola-sur: Thank you! I tried on my macbook and it works with your suggestions. Looking forward to a new release.

> ```julia
> ]remove Pigeons
> ```
> 
> and then
> 
> ```julia
> ]add https://github.com/Julia-Tempering/Pigeons.jl.git
> ```

**Comment by Gkreindler** [comment]
I can confirm that this works on Windows after getting rid of the space in the path. 🎉 
Thank you, all, we're excited to dive into learning how to use Pigeons.jl for our applications!!

**Comment by Lliillyy** [comment]
Hello,

I just updated the Pigeons package locally by 

`]add https://github.com/Julia-Tempering/Pigeons.jl.git
`

However, when I re-ran my code, the following line throws an error indicating that `create_state_initializer` is not defined

`Pigeons.create_state_initializer(my_potential::MyLogPotential, ::Inputs) = my_potential
`

`ERROR: LoadError: UndefVarError: `create_state_initializer` not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base ./Base.jl:31
 [2] top-level scope
   @ ~/Desktop/Harvard/HKS/OptimalPolicies/src/pt.jl:50
 [3] include(mod::Module, _path::String)
   @ Base ./Base.jl:457
 [4] include(x::String)
   @ OptimalPolicies ~/Desktop/OptimalPolicies/src/OptimalPolicies.jl:2
 [5] top-level scope
   @ ~/Desktop/OptimalPolicies/src/OptimalPolicies.jl:7
 [6] include
   @ ./Base.jl:457 [inlined]
 [7] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
   @ Base ./loading.jl:2045
 [8] top-level scope
   @ stdin:3
`

**Comment by miguelbiron** [comment]
Hi -- the function `create_state_initializer` is not currently defined in the Pigeons module, so it cannot be "re-defined". 

BTW, we just pushed a new release (v0.2.0) yesterday that has the up-to-date interface. You should be able to get it simply by running
```julia
]add Pigeons
```
Moreover, the docs were heavily updated too. You might want to take a look at the section on [defining the inference problem](https://julia-tempering.github.io/Pigeons.jl/dev/input-overview/). IIUC, your problem involves no PPLs but simply pure Julia code -- in which case I recommend the subsection on [this type of models](https://julia-tempering.github.io/Pigeons.jl/dev/input-julia/#input-julia), as well as looking at the more involved [Ising model example](https://github.com/Julia-Tempering/Pigeons.jl/blob/main/examples/ising.jl).

**Comment by Lliillyy** [comment]
Thank you @miguelbiron 
I've seen that the docs have been updated and they are nicely written. I'll take the time to read the updates. Has the Ising model also been updated according to the latest release?

**Comment by miguelbiron** [comment]
Absolutely -- here you can see [the old Ising model example](https://github.com/Julia-Tempering/Pigeons.jl/blob/3aaf09bdb9eb12bb0205147b41740385268f89e5/examples/custom-sampler.jl) using the old approach, and [the particular line](https://github.com/Julia-Tempering/Pigeons.jl/blob/3aaf09bdb9eb12bb0205147b41740385268f89e5/examples/custom-sampler.jl#L84) that now is failing. In contrast, the [new Ising model](https://github.com/Julia-Tempering/Pigeons.jl/blob/49c056033e059d95426d0975b270721e7f614ce7/examples/ising.jl) example features the latest [approach to initialization](https://github.com/Julia-Tempering/Pigeons.jl/blob/49c056033e059d95426d0975b270721e7f614ce7/examples/ising.jl#L85).

**Comment by Lliillyy** [comment]
This is very helpful. Thanks!

**Comment by Lliillyy** [comment]
Hi, thank you again for providing the example of custom implementation. Now I am looking at the `get_sample` method and wondering whether I can select the global chain index for plotting and sanity check. I have tried `get_sample(pt, 2)` to get the second chain but did not succeed. It seems that the function calls `SampleArray`, which is not compatible with the custom type. I'd appreciate if you could provide an example of plotting the traces of all chains when using a custom type.

**Comment by alexandrebouchard** [comment]
Thanks for pointing this out, there was indeed a gap in the doc. I just pushed a PR that should clarify how to do this: https://julia-tempering.github.io/Pigeons.jl/dev/output-custom-types/#Trace-processing-without-flattening

Let me know if anything is unclear!

**Comment by Lliillyy** [comment]
@alexandrebouchard Thanks a lot for your reply. 

I tried to employ MPI following the documentation by modifying `custom-sampler.jl` to 
```
include("ising.jl")

Pigeons.extract_sample(state::IsingState, log_potential) = copy(state.matrix)

pt = pigeons(
    target = IsingLogPotential(1.0, 5),
    record = [traces; index_process; record_default()],
    on = ChildProcess(
            dependencies = ["ising.jl"],
            n_local_mpi_processes = 4,
            n_threads = 1),
)

vector = get_sample(pt)
print(length(vector), eltype(vector))
```
and adding the following definition to `Ising.jl`
```
Base.copy(state::IsingState) =
    IsingState(state.matrix, state.sum_pair_products, state.base_length)

```

The output throws an error saying `no method matching get_sample`
```
Entangler initialized 4 MPI processes; 1 threads per process
┌ Warning: To be able to call load() to retrieve samples in-memory, use pigeons(target = ..., checkpoint = true)
└ @ Pigeons ~/.julia/packages/Pigeons/BJYuc/src/pt/checks.jl:9
────────────────────────────────────────────────────────────────────────────
  #scans       Λ        time(s)    allc(B)  log(Z₁/Z₀)   min(α)     mean(α) 
────────── ────────── ────────── ────────── ────────── ────────── ──────────
        2       4.25      0.203   1.13e+06         34    0.00753      0.528 
        4       3.37      0.331   1.92e+04       32.1    0.00701      0.626 
        8       2.12     0.0237   1.19e+05       33.5      0.274      0.764 
       16       2.93    0.00472   1.53e+05       34.1      0.421      0.674 
       32       3.17    0.00329    1.4e+05       33.5      0.564      0.647 
       64       3.23    0.00437   2.61e+05       33.5      0.504      0.642 
      128          3    0.00727   4.56e+05       33.7      0.569      0.667 
      256       2.73     0.0136   9.29e+05       33.7      0.573      0.696 
      512       2.83     0.0326   1.82e+06       33.7      0.556      0.686 
 1.02e+03       2.89     0.0633   3.68e+06       33.4      0.532      0.678 
────────────────────────────────────────────────────────────────────────────
ERROR: LoadError: MethodError: no method matching get_sample(::Result{PT})

Closest candidates are:
  get_sample(::PT)
   @ Pigeons ~/.julia/packages/Pigeons/BJYuc/src/pt/process_sample.jl:81
  get_sample(::PT, ::Int64, ::Int64)
   @ Pigeons ~/.julia/packages/Pigeons/BJYuc/src/pt/process_sample.jl:93
  get_sample(::PT, ::Any)
   @ Pigeons ~/.julia/packages/Pigeons/BJYuc/src/pt/process_sample.jl:81

Stacktrace:
 [1] top-level scope
   @ ~/Desktop/Harvard/HKS/OptimalPolicies/examples/custom-sampler.jl:28
 [2] include(fname::String)
   @ Base.MainInclude ./client.jl:478
 [3] top-level scope
   @ REPL[8]:1
in expression starting at /Users/apple/Desktop/Harvard/HKS/OptimalPolicies/examples/custom-sampler.jl:28
```

Thus, I am wondering how I shall extract the samples when the Ising example is employing the MPI. Thank you!

**Comment by alexandrebouchard** [comment]
When running on ChildProcess/MPI, you need to first load back the distributed replicas (across several processes) into the memory of your interactive node. To do this you are missing just two small things from https://pigeons.run/dev/output-mpi-postprocessing/#Loading-the-distributed-output-back-into-your-interactive-shell 

1. add the option `checkpoint = true` in your `pigeons(...)` call
2. call `pt = load(result)` on the output of `result = pigeons(...)` before doing anything with the output. 

Hope this helps!

**Comment by nikola-sur** [comment]
I hope you had success using Pigeons! May I close this issue? Feel free to post questions on a new issue if you wish :)
