### ISSUE TITLE
Documentation segfaults in CI

### ISSUE THREAD

**Issue by alexandrebouchard** [Julia-Tempering/Pigeons.jl#94]
Bad CIs:
- https://github.com/Julia-Tempering/Pigeons.jl/actions/runs/5647857586/job/15298841442#step:6:1773
- https://github.com/Julia-Tempering/Pigeons.jl/actions/runs/5647367572/job/15297333645#step:6:1738
- https://github.com/Julia-Tempering/Pigeons.jl/actions/runs/5644760187/job/15289202988#step:6:1731

**Comment by alexandrebouchard** [comment]
Some hypotheses

1. moving 1.8 to 1.9 for the documenter CI instance
2. PairPlots demands Makie alongside Plots 
3. Recent updates in DynamicPPL?

So far the problem does not arise in the tests, just in doc, so hypothesis two seems the most likely

**Comment by alexandrebouchard** [comment]
4. StatsFuns? (seems to use some crazy R bridge stuff)

**Comment by alexandrebouchard** [comment]
First commit with segfault: 

[17248ab](https://github.com/Julia-Tempering/Pigeons.jl/pull/93/commits/17248ab4c9128c4bf1dc12ddac6b4e792c31d4cb)

The one right before was OK: [b928f12](https://github.com/Julia-Tempering/Pigeons.jl/pull/93/commits/b928f1228b497b9a064fa9df72f8690415605761)

**Comment by alexandrebouchard** [comment]
After removing GLMakie and Pairplot, first build seems to work: https://github.com/Julia-Tempering/Pigeons.jl/actions/runs/5649239689/job/15303175673

**Comment by alexandrebouchard** [comment]
But another build shortly after segfaults as well: https://github.com/Julia-Tempering/Pigeons.jl/actions/runs/5650017436/job/15305570542

Confirms non-determinism of the problem.

**Comment by alexandrebouchard** [comment]
Might also be missing plotlyjs() statements?

**Comment by alexandrebouchard** [comment]
Tried downgrading doc CI to Julia 1.8

First try works https://github.com/Julia-Tempering/Pigeons.jl/actions/runs/5650289059/job/15306386317?pr=93

**Comment by alexandrebouchard** [comment]
Another successful run: https://github.com/Julia-Tempering/Pigeons.jl/actions/runs/5650895261/job/15308036897?pr=93

**Comment by miguelbiron** [comment]
Seems like it was indeed fixed by https://github.com/Julia-Tempering/Pigeons.jl/pull/93/commits/493040d63577c03a9610f653344391d0f8049ed1 . Will close for now.
